### PR TITLE
change a heading in content/_index.md

### PR DESCRIPTION
**Pull request by NickleDave**
as discussed at last meeting (17)

rename "# Developer Profiles" -> "# Tutorials" and change "Single Developer" bullet to "Getting Started with Code Review"

I felt like we agreed this was a good idea, wanted to go ahead and open discussion on a PR. 

I went with "Getting Started" since I'm thinking along the lines of docs where the tutorial would be the highest level intro, and you could have more detailed "how-to" guides (maybe that is where specifics on different "workflows" for single devs v RSE teams could go?)

### CODE REVIEW

**Comment by tlestang** [comment]
Or a single button "Get started now", or "learn more" ?

**Comment by NickleDave** [comment]
Either of those phrases sound good to me.

I guess "link in a wordy sentence" v "big button that says 'press here'" is a question of style.
I think I went with the former because I'm thinking more "book-like".

**Comment by NickleDave** [comment]
Merging for now since @tlestang approves of my logic for writing a sentence and not putting a button 😀

**Comment by NickleDave** [comment]
Except that I actually failed to change it to "getting started" ☹️  will fix

**Pull request merged**
